# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(db_column='BRA_ID', primary_key=True, serialize=False, verbose_name='Ид')),
                ('title', models.CharField(blank=True, db_column='BRA_BRAND', max_length=60, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, db_column='BRA_MFC_CODE', max_length=30, null=True, verbose_name='Название')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['title'],
                'managed': False,
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(db_column='COU_ID', primary_key=True, serialize=False, verbose_name='Ид')),
                ('iso_code', models.CharField(blank=True, db_column='COU_ISO2', max_length=6, null=True, verbose_name='Код ISO2')),
                ('currency_code', models.CharField(blank=True, db_column='COU_CURRENCY_CODE', max_length=9, null=True, verbose_name='Код Валюты')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'managed': False,
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='CountryDesignation',
            fields=[
                ('id', models.AutoField(db_column='CDS_ID', primary_key=True, serialize=False, verbose_name='Ид')),
            ],
            options={
                'abstract': False,
                'managed': False,
                'db_table': 'country_designations',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(db_column='TEX_ID', primary_key=True, serialize=False, verbose_name='Ид')),
                ('text', models.TextField(db_column='TEX_TEXT', verbose_name='Текст')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Текст обозначения',
                'managed': False,
                'db_table': 'des_texts',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(db_column='DES_ID', primary_key=True, serialize=False, verbose_name='Ид')),
            ],
            options={
                'abstract': False,
                'managed': False,
                'db_table': 'designations',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(db_column='LNG_ID', primary_key=True, serialize=False, verbose_name='Ид')),
                ('iso_code', models.CharField(blank=True, db_column='LNG_ISO2', max_length=6, null=True, verbose_name='Код ISO2')),
                ('codepage', models.CharField(blank=True, db_column='LNG_CODEPAGE', max_length=30, null=True, verbose_name='Кодировка')),
            ],
            options={
                'abstract': False,
                'managed': False,
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(db_column='MFA_ID', primary_key=True, serialize=False, verbose_name='Ид')),
                ('title', models.CharField(blank=True, db_column='MFA_BRAND', max_length=60, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, db_column='MFA_MFC_CODE', max_length=30, null=True, verbose_name='Код')),
                ('for_car', models.SmallIntegerField(blank=True, choices=[('0', 'Нет'), ('1', 'Да')], db_column='MFA_PC_MFC', null=True, verbose_name='Для легковых')),
                ('for_truck', models.SmallIntegerField(blank=True, choices=[('0', 'Нет'), ('1', 'Да')], db_column='MFA_CV_MFC', null=True, verbose_name='Для грузовых')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Производитель автомобилей',
                'verbose_name_plural': 'Производители автомобилей',
                'ordering': ['title'],
                'managed': False,
                'db_table': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(db_column='TMT_ID', primary_key=True, serialize=False, verbose_name='Ид')),
                ('text', models.TextField(db_column='TMT_TEXT', null=True, verbose_name='Текст')),
            ],
            options={
                'abstract': False,
                'managed': False,
                'db_table': 'text_module_texts',
            },
        ),
        migrations.CreateModel(
            name='TextModule',
            fields=[
                ('id', models.AutoField(db_column='TMO_ID', primary_key=True, serialize=False, verbose_name='Ид')),
            ],
            options={
                'abstract': False,
                'managed': False,
                'db_table': 'text_modules',
            },
        ),
    ]
